--password: test123
INSERT INTO USERS (ID,USERNAME,PASSWORD,ROLE,VERSION)
VALUES (1,'admin','$2y$12$JB.LEflCp3cniYnXSfb6KO4NXYcIHseGLfKEL5STkszrplNY1MBfW','ROLE_ADMIN',1);
--password: user123
INSERT INTO USERS (ID,USERNAME,PASSWORD,ROLE,VERSION)
VALUES (2,'user','$2y$12$7Y4dZAj/sMGUWw.T5rJ56evND3SAsahn6JcyqbF4gikirp3Q/f322','ROLE_USER',1);

INSERT INTO CARS (ID,BRAND,COST,COLOR,MODEL,NAME,SEAT,TYPE,VEHICLE_LICENSE,VERSION,CREATED_DATE)
VALUES (1,'Toyota',10000,'Blue','2015','Innova',5,'Small','INNO45866FX',1,CURRENT_TIMESTAMP());

INSERT INTO CARS (ID,BRAND,COST,COLOR,MODEL,NAME,SEAT,TYPE,VEHICLE_LICENSE,VERSION,CREATED_DATE)
VALUES (2,'Toyota',15000,'Gray','2017','Fortuner',7,'Medium','FTNR32871SA',1,CURRENT_TIMESTAMP());

INSERT INTO CARS (ID,BRAND,COST,COLOR,MODEL,NAME,SEAT,TYPE,VEHICLE_LICENSE,VERSION,CREATED_DATE)
VALUES (3,'BMW',20000,'Black','2016','M3','4','Small','M3BM23187BM',1,CURRENT_TIMESTAMP());

INSERT INTO CARS (ID,BRAND,COST,COLOR,MODEL,NAME,SEAT,TYPE,VEHICLE_LICENSE,VERSION,CREATED_DATE)
VALUES (4,'BMW',20000,'White','2018','M5','4','Small','M5BM56977BM',1,CURRENT_TIMESTAMP());

INSERT INTO CARS (ID,BRAND,COST,COLOR,MODEL,NAME,SEAT,TYPE,VEHICLE_LICENSE,VERSION,CREATED_DATE)
VALUES (5,'BMW',26000,'Red','2016','Z4','2','Small','Z4BM663582BM',1,CURRENT_TIMESTAMP());